/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Practica3;

import java.io.IOException;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

/**
 *
 * @author usuario
 */
public class Practica3 extends javax.swing.JFrame {

    Random generarNumero = new Random();
    int aciertos = 0;
    String caracteres;
    String caracteres2;

    public Practica3() {
        initComponents();
        jToggleButton1.setEnabled(false);
        jToggleButton20.setEnabled(false);
        jToggleButton24.setEnabled(false);
        jToggleButton28.setEnabled(false);
        jToggleButton18.setEnabled(false);
        jToggleButton21.setEnabled(false);
        jToggleButton25.setEnabled(false);
        jToggleButton29.setEnabled(false);
        jToggleButton17.setEnabled(false);
        jToggleButton22.setEnabled(false);
        jToggleButton26.setEnabled(false);
        jToggleButton30.setEnabled(false);
        jToggleButton19.setEnabled(false);
        jToggleButton23.setEnabled(false);
        jToggleButton27.setEnabled(false);
        jToggleButton31.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton17 = new javax.swing.JToggleButton();
        jToggleButton18 = new javax.swing.JToggleButton();
        jToggleButton19 = new javax.swing.JToggleButton();
        jToggleButton20 = new javax.swing.JToggleButton();
        jToggleButton21 = new javax.swing.JToggleButton();
        jToggleButton22 = new javax.swing.JToggleButton();
        jToggleButton23 = new javax.swing.JToggleButton();
        jToggleButton24 = new javax.swing.JToggleButton();
        jToggleButton25 = new javax.swing.JToggleButton();
        jToggleButton26 = new javax.swing.JToggleButton();
        jToggleButton27 = new javax.swing.JToggleButton();
        jToggleButton28 = new javax.swing.JToggleButton();
        jToggleButton29 = new javax.swing.JToggleButton();
        jToggleButton30 = new javax.swing.JToggleButton();
        jToggleButton31 = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Z.png"))); // NOI18N
        jLabel2.setMaximumSize(new java.awt.Dimension(97, 73));
        jLabel2.setMinimumSize(new java.awt.Dimension(97, 73));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Z.png"))); // NOI18N

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Z.png"))); // NOI18N
        jLabel6.setMaximumSize(new java.awt.Dimension(97, 73));
        jLabel6.setMinimumSize(new java.awt.Dimension(97, 73));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Z.png"))); // NOI18N
        jLabel7.setMaximumSize(new java.awt.Dimension(97, 73));
        jLabel7.setMinimumSize(new java.awt.Dimension(97, 73));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Z.png"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Z.png"))); // NOI18N
        jLabel4.setMaximumSize(new java.awt.Dimension(97, 73));
        jLabel4.setMinimumSize(new java.awt.Dimension(97, 73));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Z.png"))); // NOI18N
        jLabel9.setMaximumSize(new java.awt.Dimension(97, 73));
        jLabel9.setMinimumSize(new java.awt.Dimension(97, 73));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(68, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton1.setText("Empezar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Recordar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Comprobar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Aciertos");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jToggleButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Z.png"))); // NOI18N

        jToggleButton17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Z.png"))); // NOI18N

        jToggleButton18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Z.png"))); // NOI18N

        jToggleButton19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Z.png"))); // NOI18N

        jToggleButton20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Z.png"))); // NOI18N

        jToggleButton21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Z.png"))); // NOI18N

        jToggleButton22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Z.png"))); // NOI18N

        jToggleButton23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Z.png"))); // NOI18N

        jToggleButton24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Z.png"))); // NOI18N

        jToggleButton25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Z.png"))); // NOI18N

        jToggleButton26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Z.png"))); // NOI18N

        jToggleButton27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Z.png"))); // NOI18N

        jToggleButton28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Z.png"))); // NOI18N

        jToggleButton29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Z.png"))); // NOI18N

        jToggleButton30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Z.png"))); // NOI18N

        jToggleButton31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Z.png"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jToggleButton17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jToggleButton18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jToggleButton19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jToggleButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToggleButton20)
                    .addComponent(jToggleButton22)
                    .addComponent(jToggleButton21)
                    .addComponent(jToggleButton23))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToggleButton24)
                    .addComponent(jToggleButton26)
                    .addComponent(jToggleButton25)
                    .addComponent(jToggleButton27))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToggleButton28)
                    .addComponent(jToggleButton30)
                    .addComponent(jToggleButton29)
                    .addComponent(jToggleButton31))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jToggleButton28)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton29)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton30)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton31))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jToggleButton24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton27))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(jToggleButton20)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jToggleButton21)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jToggleButton22)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jToggleButton23))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(jToggleButton1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jToggleButton18)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jToggleButton17)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jToggleButton19))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jToggleButton1.setEnabled(false);
        jToggleButton20.setEnabled(false);
        jToggleButton24.setEnabled(false);
        jToggleButton28.setEnabled(false);
        jToggleButton18.setEnabled(false);
        jToggleButton21.setEnabled(false);
        jToggleButton25.setEnabled(false);
        jToggleButton29.setEnabled(false);
        jToggleButton17.setEnabled(false);
        jToggleButton22.setEnabled(false);
        jToggleButton26.setEnabled(false);
        jToggleButton30.setEnabled(false);
        jToggleButton19.setEnabled(false);
        jToggleButton23.setEnabled(false);
        jToggleButton27.setEnabled(false);
        jToggleButton31.setEnabled(false);
        jToggleButton1.setSelected(false);
        jToggleButton20.setSelected(false);
        jToggleButton24.setSelected(false);
        jToggleButton28.setSelected(false);
        jToggleButton18.setSelected(false);
        jToggleButton21.setSelected(false);
        jToggleButton25.setSelected(false);
        jToggleButton29.setSelected(false);
        jToggleButton17.setSelected(false);
        jToggleButton22.setSelected(false);
        jToggleButton26.setSelected(false);
        jToggleButton30.setSelected(false);
        jToggleButton19.setSelected(false);
        jToggleButton23.setSelected(false);
        jToggleButton27.setSelected(false);
        jToggleButton31.setSelected(false);
        aciertos = 0;
        caracteres = "";
        for (int i = 0; i <= 7; i++) {
            int numero1 = generarNumero.nextInt(16) + 65;
            caracteres += (char) numero1;
        }

        try {
            jLabel5.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("/Imagenes/" + caracteres.charAt(0) + ".png"))));
            jLabel2.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("/Imagenes/" + caracteres.charAt(1) + ".png"))));
            jLabel6.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("/Imagenes/" + caracteres.charAt(2) + ".png"))));
            jLabel7.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("/Imagenes/" + caracteres.charAt(3) + ".png"))));
            if (aciertos == 4) {
                jLabel8.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("/Imagenes/" + caracteres.charAt(4) + ".png"))));
            }
            if (aciertos == 5) {
                jLabel4.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("/Imagenes/" + caracteres.charAt(5) + ".png"))));
            }
            if (aciertos == 6) {
                jLabel9.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("/Imagenes/" + caracteres.charAt(6) + ".png"))));
            }
        } catch (IOException ex) {
            Logger.getLogger(Practica3.class.getName()).log(Level.SEVERE, null, ex);
        }
        jLabel3.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jToggleButton1.setEnabled(true);
        jToggleButton20.setEnabled(true);
        jToggleButton24.setEnabled(true);
        jToggleButton28.setEnabled(true);
        jToggleButton18.setEnabled(true);
        jToggleButton21.setEnabled(true);
        jToggleButton25.setEnabled(true);
        jToggleButton29.setEnabled(true);
        jToggleButton17.setEnabled(true);
        jToggleButton22.setEnabled(true);
        jToggleButton26.setEnabled(true);
        jToggleButton30.setEnabled(true);
        jToggleButton19.setEnabled(true);
        jToggleButton23.setEnabled(true);
        jToggleButton27.setEnabled(true);
        jToggleButton31.setEnabled(true);
        caracteres2 = "";
        for (int i = 0; i <= 16; i++) {
            int numero2 = generarNumero.nextInt(16) + 65;
            caracteres2 += (char) numero2;
        }
        try {
            jToggleButton1.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("/Imagenes/" + caracteres2.charAt(0) + ".png"))));
            jToggleButton20.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("/Imagenes/" + caracteres2.charAt(1) + ".png"))));
            jToggleButton24.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("/Imagenes/" + caracteres2.charAt(2) + ".png"))));
            jToggleButton28.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("/Imagenes/" + caracteres2.charAt(3) + ".png"))));
            jToggleButton18.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("/Imagenes/" + caracteres2.charAt(4) + ".png"))));
            jToggleButton21.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("/Imagenes/" + caracteres2.charAt(5) + ".png"))));
            jToggleButton25.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("/Imagenes/" + caracteres2.charAt(6) + ".png"))));
            jToggleButton29.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("/Imagenes/" + caracteres2.charAt(7) + ".png"))));
            jToggleButton17.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("/Imagenes/" + caracteres2.charAt(8) + ".png"))));
            jToggleButton22.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("/Imagenes/" + caracteres2.charAt(9) + ".png"))));
            jToggleButton26.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("/Imagenes/" + caracteres2.charAt(10) + ".png"))));
            jToggleButton30.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("/Imagenes/" + caracteres2.charAt(11) + ".png"))));
            jToggleButton19.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("/Imagenes/" + caracteres2.charAt(12) + ".png"))));
            jToggleButton23.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("/Imagenes/" + caracteres2.charAt(13) + ".png"))));
            jToggleButton27.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("/Imagenes/" + caracteres2.charAt(14) + ".png"))));
            jToggleButton31.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("/Imagenes/" + caracteres2.charAt(15) + ".png"))));
            jLabel5.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("/Imagenes/Z.png"))));
            jLabel2.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("/Imagenes/Z.png"))));
            jLabel6.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("/Imagenes/Z.png"))));
            jLabel7.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("/Imagenes/Z.png"))));
            jLabel8.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("/Imagenes/Z.png"))));
            jLabel4.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("/Imagenes/Z.png"))));
            jLabel9.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("/Imagenes/Z.png"))));
        } catch (IOException ex) {
            Logger.getLogger(Practica3.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int valor1 = caracteres.indexOf(caracteres2.charAt(0));
        int valor2 = caracteres.indexOf(caracteres2.charAt(1));
        int valor3 = caracteres.indexOf(caracteres2.charAt(2));
        int valor4 = caracteres.indexOf(caracteres2.charAt(3));
        int valor5 = caracteres.indexOf(caracteres2.charAt(4));
        int valor6 = caracteres.indexOf(caracteres2.charAt(5));
        int valor7 = caracteres.indexOf(caracteres2.charAt(6));
        int valor8 = caracteres.indexOf(caracteres2.charAt(7));
        int valor9 = caracteres.indexOf(caracteres2.charAt(8));
        int valor10 = caracteres.indexOf(caracteres2.charAt(9));
        int valor11 = caracteres.indexOf(caracteres2.charAt(10));
        int valor12 = caracteres.indexOf(caracteres2.charAt(11));
        int valor13 = caracteres.indexOf(caracteres2.charAt(12));
        int valor14 = caracteres.indexOf(caracteres2.charAt(13));
        int valor15 = caracteres.indexOf(caracteres2.charAt(14));
        int valor16 = caracteres.indexOf(caracteres2.charAt(15));

        if (jToggleButton1.isSelected() && valor1 != -1) {
            aciertos++;
        } else {
            jToggleButton1.setEnabled(false);
        }
        if (jToggleButton20.isSelected() && valor2 != -1) {
            aciertos++;
        } else {
            jToggleButton20.setEnabled(false);
        }
        if (jToggleButton24.isSelected() && valor3 != -1) {
            aciertos++;
        } else {
            jToggleButton24.setEnabled(false);
        }
        if (jToggleButton28.isSelected() && valor4 != -1) {
            aciertos++;
        } else {
            jToggleButton28.setEnabled(false);
        }
        if (jToggleButton18.isSelected() && valor5 != -1) {
            aciertos++;
        } else {
            jToggleButton18.setEnabled(false);
        }
        if (jToggleButton21.isSelected() && valor6 != -1) {
            aciertos++;
        } else {
            jToggleButton21.setEnabled(false);
        }
        if (jToggleButton25.isSelected() && valor7 != -1) {
            aciertos++;
        } else {
            jToggleButton25.setEnabled(false);
        }
        if (jToggleButton29.isSelected() && valor8 != -1) {
            aciertos++;
        } else {
            jToggleButton29.setEnabled(false);
        }
        if (jToggleButton17.isSelected() && valor9 != -1) {
            aciertos++;
        } else {
            jToggleButton17.setEnabled(false);
        }
        if (jToggleButton22.isSelected() && valor10 != -1) {
            aciertos++;
        } else {
            jToggleButton22.setEnabled(false);
        }
        if (jToggleButton26.isSelected() && valor11 != -1) {
            aciertos++;
        } else {
            jToggleButton26.setEnabled(false);
        }
        if (jToggleButton30.isSelected() && valor12 != -1) {
            aciertos++;
        } else {
            jToggleButton30.setEnabled(false);
        }
        if (jToggleButton19.isSelected() && valor13 != -1) {
            aciertos++;
        } else {
            jToggleButton19.setEnabled(false);
        }
        if (jToggleButton23.isSelected() && valor14 != -1) {
            aciertos++;
        } else {
            jToggleButton23.setEnabled(false);
        }
        if (jToggleButton27.isSelected() && valor15 != -1) {
            aciertos++;
        } else {
            jToggleButton27.setEnabled(false);
        }
        if (jToggleButton31.isSelected() && valor16 != -1) {
            aciertos++;
        } else {
            jToggleButton31.setEnabled(false);
        }
        jLabel3.setText("" + aciertos);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Practica3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Practica3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Practica3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Practica3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Practica3().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton17;
    private javax.swing.JToggleButton jToggleButton18;
    private javax.swing.JToggleButton jToggleButton19;
    private javax.swing.JToggleButton jToggleButton20;
    private javax.swing.JToggleButton jToggleButton21;
    private javax.swing.JToggleButton jToggleButton22;
    private javax.swing.JToggleButton jToggleButton23;
    private javax.swing.JToggleButton jToggleButton24;
    private javax.swing.JToggleButton jToggleButton25;
    private javax.swing.JToggleButton jToggleButton26;
    private javax.swing.JToggleButton jToggleButton27;
    private javax.swing.JToggleButton jToggleButton28;
    private javax.swing.JToggleButton jToggleButton29;
    private javax.swing.JToggleButton jToggleButton30;
    private javax.swing.JToggleButton jToggleButton31;
    // End of variables declaration//GEN-END:variables
}
