/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Practica3;

import java.io.IOException;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

/**
 *
 * @author usuario
 */
public class Practica3 extends javax.swing.JFrame {

    /**
     * Creates new form Practica3
     */
    public Practica3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton17 = new javax.swing.JToggleButton();
        jToggleButton18 = new javax.swing.JToggleButton();
        jToggleButton19 = new javax.swing.JToggleButton();
        jToggleButton20 = new javax.swing.JToggleButton();
        jToggleButton21 = new javax.swing.JToggleButton();
        jToggleButton22 = new javax.swing.JToggleButton();
        jToggleButton23 = new javax.swing.JToggleButton();
        jToggleButton24 = new javax.swing.JToggleButton();
        jToggleButton25 = new javax.swing.JToggleButton();
        jToggleButton26 = new javax.swing.JToggleButton();
        jToggleButton27 = new javax.swing.JToggleButton();
        jToggleButton28 = new javax.swing.JToggleButton();
        jToggleButton29 = new javax.swing.JToggleButton();
        jToggleButton30 = new javax.swing.JToggleButton();
        jToggleButton31 = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Z.png"))); // NOI18N
        jLabel2.setMaximumSize(new java.awt.Dimension(97, 73));
        jLabel2.setMinimumSize(new java.awt.Dimension(97, 73));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Z.png"))); // NOI18N
        jLabel5.setMaximumSize(new java.awt.Dimension(97, 73));
        jLabel5.setMinimumSize(new java.awt.Dimension(97, 73));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Z.png"))); // NOI18N
        jLabel6.setMaximumSize(new java.awt.Dimension(97, 73));
        jLabel6.setMinimumSize(new java.awt.Dimension(97, 73));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Z.png"))); // NOI18N
        jLabel7.setMaximumSize(new java.awt.Dimension(97, 73));
        jLabel7.setMinimumSize(new java.awt.Dimension(97, 73));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("jButton2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jToggleButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Z.png"))); // NOI18N

        jToggleButton17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Z.png"))); // NOI18N

        jToggleButton18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Z.png"))); // NOI18N

        jToggleButton19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Z.png"))); // NOI18N

        jToggleButton20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Z.png"))); // NOI18N

        jToggleButton21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Z.png"))); // NOI18N

        jToggleButton22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Z.png"))); // NOI18N

        jToggleButton23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Z.png"))); // NOI18N

        jToggleButton24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Z.png"))); // NOI18N

        jToggleButton25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Z.png"))); // NOI18N

        jToggleButton26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Z.png"))); // NOI18N

        jToggleButton27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Z.png"))); // NOI18N

        jToggleButton28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Z.png"))); // NOI18N

        jToggleButton29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Z.png"))); // NOI18N

        jToggleButton30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Z.png"))); // NOI18N

        jToggleButton31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Z.png"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jToggleButton17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jToggleButton18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jToggleButton19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jToggleButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToggleButton20)
                    .addComponent(jToggleButton22)
                    .addComponent(jToggleButton21)
                    .addComponent(jToggleButton23))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToggleButton24)
                    .addComponent(jToggleButton26)
                    .addComponent(jToggleButton25)
                    .addComponent(jToggleButton27))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToggleButton28)
                    .addComponent(jToggleButton30)
                    .addComponent(jToggleButton29)
                    .addComponent(jToggleButton31))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jToggleButton28)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton29)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton30)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton31))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jToggleButton24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton27))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(jToggleButton20)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jToggleButton21)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jToggleButton22)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jToggleButton23))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(jToggleButton1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jToggleButton18)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jToggleButton17)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jToggleButton19))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Random generarNumero = new Random();
        ImageIcon imagen1;
        ImageIcon imagen2;
        ImageIcon imagen3;
        ImageIcon imagen4;
        char letras1, letras2, letras3, letras4;
        jToggleButton1.setEnabled(false);
        jToggleButton20.setEnabled(false);
        jToggleButton24.setEnabled(false);
        jToggleButton28.setEnabled(false);
        jToggleButton18.setEnabled(false);
        jToggleButton21.setEnabled(false);
        jToggleButton25.setEnabled(false);
        jToggleButton29.setEnabled(false);
        jToggleButton17.setEnabled(false);
        jToggleButton22.setEnabled(false);
        jToggleButton26.setEnabled(false);
        jToggleButton30.setEnabled(false);
        jToggleButton19.setEnabled(false);
        jToggleButton23.setEnabled(false);
        jToggleButton27.setEnabled(false);
        jToggleButton31.setEnabled(false);
        jToggleButton1.setSelected(false);
        jToggleButton20.setSelected(false);
        jToggleButton24.setSelected(false);
        jToggleButton28.setSelected(false);
        jToggleButton18.setSelected(false);
        jToggleButton21.setSelected(false);
        jToggleButton25.setSelected(false);
        jToggleButton29.setSelected(false);
        jToggleButton17.setSelected(false);
        jToggleButton22.setSelected(false);
        jToggleButton26.setSelected(false);
        jToggleButton30.setSelected(false);
        jToggleButton19.setSelected(false);
        jToggleButton23.setSelected(false);
        jToggleButton27.setSelected(false);
        jToggleButton31.setSelected(false);
        try {
            int numero1 = generarNumero.nextInt(15) + 65;
            int numero2 = generarNumero.nextInt(15) + 65;
            int numero3 = generarNumero.nextInt(15) + 65;
            int numero4 = generarNumero.nextInt(15) + 65;
            System.out.println(numero1);
            System.out.println(numero2);
            System.out.println(numero3);
            System.out.println(numero4);
            letras1 = (char) numero1;
            letras2 = (char) numero2;
            letras3 = (char) numero3;
            letras4 = (char) numero4;
            System.out.println(letras1);
            System.out.println(letras2);
            System.out.println(letras3);
            System.out.println(letras4);
            jLabel5.setIcon(imagen1 = new ImageIcon(ImageIO.read(getClass().getResource("/Imagenes/" + letras1 + ".png"))));
            jLabel2.setIcon(imagen2 = new ImageIcon(ImageIO.read(getClass().getResource("/Imagenes/" + letras2 + ".png"))));
            jLabel6.setIcon(imagen3 = new ImageIcon(ImageIO.read(getClass().getResource("/Imagenes/" + letras3 + ".png"))));
            jLabel7.setIcon(imagen4 = new ImageIcon(ImageIO.read(getClass().getResource("/Imagenes/" + letras4 + ".png"))));

        } catch (IOException ex) {
            Logger.getLogger(Practica3.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Random generarNumero = new Random();
        ImageIcon imagen1, imagen2, imagen3, imagen4, imagen5, imagen6, imagen7, imagen8;
        ImageIcon imagen9, imagen10, imagen11, imagen12, imagen13, imagen14, imagen15, imagen16;

        char letras1, letras2, letras3, letras4, letras5, letras6, letras7, letras8;
        char letras9, letras10, letras11, letras12, letras13, letras14, letras15, letras16;

            jToggleButton1.setEnabled(true);
            jToggleButton20.setEnabled(true);
            jToggleButton24.setEnabled(true);
            jToggleButton28.setEnabled(true);
            jToggleButton18.setEnabled(true);
            jToggleButton21.setEnabled(true);
            jToggleButton25.setEnabled(true);
            jToggleButton29.setEnabled(true);
            jToggleButton17.setEnabled(true);
            jToggleButton22.setEnabled(true);
            jToggleButton26.setEnabled(true);
            jToggleButton30.setEnabled(true);
            jToggleButton19.setEnabled(true);
            jToggleButton23.setEnabled(true);
            jToggleButton27.setEnabled(true);
            jToggleButton31.setEnabled(true);

        try {
            int numero1 = generarNumero.nextInt(15) + 65;
            int numero2 = generarNumero.nextInt(15) + 65;
            int numero3 = generarNumero.nextInt(15) + 65;
            int numero4 = generarNumero.nextInt(15) + 65;
            int numero5 = generarNumero.nextInt(15) + 65;
            int numero6 = generarNumero.nextInt(15) + 65;
            int numero7 = generarNumero.nextInt(15) + 65;
            int numero8 = generarNumero.nextInt(15) + 65;
            int numero9 = generarNumero.nextInt(15) + 65;
            int numero10 = generarNumero.nextInt(15) + 65;
            int numero11 = generarNumero.nextInt(15) + 65;
            int numero12 = generarNumero.nextInt(15) + 65;
            int numero13 = generarNumero.nextInt(15) + 65;
            int numero14 = generarNumero.nextInt(15) + 65;
            int numero15 = generarNumero.nextInt(15) + 65;
            int numero16 = generarNumero.nextInt(15) + 65;
            letras1 = (char) numero1;
            letras2 = (char) numero2;
            letras3 = (char) numero3;
            letras4 = (char) numero4;
            letras5 = (char) numero5;
            letras6 = (char) numero6;
            letras7 = (char) numero7;
            letras8 = (char) numero8;
            letras9 = (char) numero9;
            letras10 = (char) numero10;
            letras11 = (char) numero11;
            letras12 = (char) numero12;
            letras13 = (char) numero13;
            letras14 = (char) numero14;
            letras15 = (char) numero15;
            letras16 = (char) numero16;
            jToggleButton1.setIcon(imagen1 = new ImageIcon(ImageIO.read(getClass().getResource("/Imagenes/" + letras1 + ".png"))));
            jToggleButton20.setIcon(imagen2 = new ImageIcon(ImageIO.read(getClass().getResource("/Imagenes/" + letras2 + ".png"))));
            jToggleButton24.setIcon(imagen3 = new ImageIcon(ImageIO.read(getClass().getResource("/Imagenes/" + letras3 + ".png"))));
            jToggleButton28.setIcon(imagen4 = new ImageIcon(ImageIO.read(getClass().getResource("/Imagenes/" + letras4 + ".png"))));
            jToggleButton18.setIcon(imagen5 = new ImageIcon(ImageIO.read(getClass().getResource("/Imagenes/" + letras5 + ".png"))));
            jToggleButton21.setIcon(imagen6 = new ImageIcon(ImageIO.read(getClass().getResource("/Imagenes/" + letras6 + ".png"))));
            jToggleButton25.setIcon(imagen7 = new ImageIcon(ImageIO.read(getClass().getResource("/Imagenes/" + letras7 + ".png"))));
            jToggleButton29.setIcon(imagen8 = new ImageIcon(ImageIO.read(getClass().getResource("/Imagenes/" + letras8 + ".png"))));
            jToggleButton17.setIcon(imagen9 = new ImageIcon(ImageIO.read(getClass().getResource("/Imagenes/" + letras9 + ".png"))));
            jToggleButton22.setIcon(imagen10 = new ImageIcon(ImageIO.read(getClass().getResource("/Imagenes/" + letras10 + ".png"))));
            jToggleButton26.setIcon(imagen11 = new ImageIcon(ImageIO.read(getClass().getResource("/Imagenes/" + letras11 + ".png"))));
            jToggleButton30.setIcon(imagen12 = new ImageIcon(ImageIO.read(getClass().getResource("/Imagenes/" + letras12 + ".png"))));
            jToggleButton19.setIcon(imagen13 = new ImageIcon(ImageIO.read(getClass().getResource("/Imagenes/" + letras13 + ".png"))));
            jToggleButton23.setIcon(imagen14 = new ImageIcon(ImageIO.read(getClass().getResource("/Imagenes/" + letras14 + ".png"))));
            jToggleButton27.setIcon(imagen15 = new ImageIcon(ImageIO.read(getClass().getResource("/Imagenes/" + letras15 + ".png"))));
            jToggleButton31.setIcon(imagen16 = new ImageIcon(ImageIO.read(getClass().getResource("/Imagenes/" + letras15 + ".png"))));

        } catch (IOException ex) {
            Logger.getLogger(Practica3.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Practica3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Practica3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Practica3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Practica3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Practica3().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton17;
    private javax.swing.JToggleButton jToggleButton18;
    private javax.swing.JToggleButton jToggleButton19;
    private javax.swing.JToggleButton jToggleButton20;
    private javax.swing.JToggleButton jToggleButton21;
    private javax.swing.JToggleButton jToggleButton22;
    private javax.swing.JToggleButton jToggleButton23;
    private javax.swing.JToggleButton jToggleButton24;
    private javax.swing.JToggleButton jToggleButton25;
    private javax.swing.JToggleButton jToggleButton26;
    private javax.swing.JToggleButton jToggleButton27;
    private javax.swing.JToggleButton jToggleButton28;
    private javax.swing.JToggleButton jToggleButton29;
    private javax.swing.JToggleButton jToggleButton30;
    private javax.swing.JToggleButton jToggleButton31;
    // End of variables declaration//GEN-END:variables
}
